import { createDb } from "./client.js";
import { companies, agents } from "./schema/index.js";

const url = process.env.DATABASE_URL;
if (!url) throw new Error("DATABASE_URL is required");

const db = createDb(url);

console.log("Seeding Galyarder Digital Company (Hierarchical Model)...");

const [company] = await db
  .insert(companies)
  .values({
    name: "Galyarder Digital Company",
    description: "1-Man Army Executive Control Plane.",
    status: "active",
    brandColor: "#06b6d4",
    issuePrefix: "GAL",
    budgetMonthlyCents: 1000000,
  })
  .returning();

const companyId = company!.id;

// 1. Create Department Leads first
const leadMap: Record<string, string> = {};

const [super_architect] = await db.insert(agents).values({
  companyId,
  name: "super-architect",
  role: "manager",
  title: "Head of Super",
  status: "idle",
  capabilities: "Software architecture specialist for system design, scalability, and technical decision-making. Produces ADRs, Vertical Slice plans, and enforces deep module design for the 1-Man Army pipeline. Contains the full knowledge of Architecture Patterns, Systems Design, and Planning.",
  adapterType: "process",
  adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "super-architect.md"] },
  budgetMonthlyCents: 100000,
}).returning();
leadMap["super-architect"] = super_architect!.id;

const [growth_strategist] = await db.insert(agents).values({
  companyId,
  name: "growth-strategist",
  role: "manager",
  title: "Head of Growth",
  status: "idle",
  capabilities: "|   Chief Marketing Officer (CMO) specialist for SEO, CRO, Marketing Psychology, and Copywriting. Applies PLFS scoring to maximize revenue leverage and ensure every feature launch achieves market fit. Contains full knowledge of SEO Audit, Onboarding CRO, and Psychology.",
  adapterType: "process",
  adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "growth-strategist.md"] },
  budgetMonthlyCents: 100000,
}).returning();
leadMap["growth-strategist"] = growth_strategist!.id;

const [product_manager] = await db.insert(agents).values({
  companyId,
  name: "product-manager",
  role: "manager",
  title: "Head of Product",
  status: "idle",
  capabilities: "Product Management specialist. Focuses on ROI, feature prioritization, Linear ticket management, and ensuring engineering efforts directly impact user acquisition or revenue. Use PROACTIVELY before any code is written to convert PRDs into actionable Linear Epics and Issues.",
  adapterType: "process",
  adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "product-manager.md"] },
  budgetMonthlyCents: 100000,
}).returning();
leadMap["product-manager"] = product_manager!.id;

const [security_guardian] = await db.insert(agents).values({
  companyId,
  name: "security-guardian",
  role: "manager",
  title: "Head of Security",
  status: "idle",
  capabilities: "Security vulnerability detection and remediation specialist. Audits code for OWASP Top 10, IDOR, SSRF, and injection. Enforces zero trust and secure data handling for financial and AI platforms. Contains full knowledge of security reviewer and audit checklists.",
  adapterType: "process",
  adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "security-guardian.md"] },
  budgetMonthlyCents: 100000,
}).returning();
leadMap["security-guardian"] = security_guardian!.id;

const [fundraising_operator] = await db.insert(agents).values({
  companyId,
  name: "fundraising-operator",
  role: "manager",
  title: "Head of Fundraising",
  status: "idle",
  capabilities: "Fundraising and investor operations specialist. Owns founder context, pitch narrative, investor targeting, investor communication, diligence readiness, and board-update hygiene for the 1-Man Army founder.",
  adapterType: "process",
  adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "fundraising-operator.md"] },
  budgetMonthlyCents: 100000,
}).returning();
leadMap["fundraising-operator"] = fundraising_operator!.id;

const [legal_counsel] = await db.insert(agents).values({
  companyId,
  name: "legal-counsel",
  role: "manager",
  title: "Head of Legal",
  status: "idle",
  capabilities: "Legal & Compliance Specialist. Use this agent to generate TOS/Privacy policies, audit GDPR/CCPA compliance, review open-source licenses, and ensure AI governance (ISO 42001). It protects the 1-Man Army from legal liabilities.",
  adapterType: "process",
  adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "legal-counsel.md"] },
  budgetMonthlyCents: 100000,
}).returning();
leadMap["legal-counsel"] = legal_counsel!.id;

const [finops_manager] = await db.insert(agents).values({
  companyId,
  name: "finops-manager",
  role: "manager",
  title: "Head of Finops",
  status: "idle",
  capabilities: "Finance & Cloud Cost Specialist. Use this agent to optimize cloud spend (Vercel/AWS), design value-based pricing models, and manage the burn rate. It ensures the 1-Man Army remains profitable and financially sustainable.",
  adapterType: "process",
  adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "finops-manager.md"] },
  budgetMonthlyCents: 100000,
}).returning();
leadMap["finops-manager"] = finops_manager!.id;

const [obsidian_architect] = await db.insert(agents).values({
  companyId,
  name: "obsidian-architect",
  role: "manager",
  title: "Head of Obsidian",
  status: "idle",
  capabilities: "|   Digital Garden & Visual Architect. Use this agent to manage the Obsidian Knowledge Base, create visual logic maps via JSON Canvas, and maintain the automated development journal. It bridges the gap between abstract ideas and structured documentation. When the host supports them, use the Obsidian-focused skills and integrations for CLI, Bases, Markdown, Canvas, and defuddling workflows. When the host supports them, use the Obsidian-focused skills and integrations for CLI, Bases, Markdown, Canvas, and defuddling workflows.",
  adapterType: "process",
  adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "obsidian-architect.md"] },
  budgetMonthlyCents: 100000,
}).returning();
leadMap["obsidian-architect"] = obsidian_architect!.id;

// 2. Create Staff and map to Leads
await db.insert(agents).values([
  {
    companyId,
    name: "analytics-architect",
    role: "staff",
    title: "Analytics Architect",
    status: "idle",
    reportsTo: leadMap['growth-strategist'],
    capabilities: "Data Infrastructure & Tracking Specialist. Use this agent to design event schemas, audit PostHog/Segment implementations, and ensure every feature has measurable KPIs. It focuses on the \"Measure\" part of the Build-Measure-Learn loop.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "analytics-architect.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "architect",
    role: "staff",
    title: "Architect",
    status: "idle",
    reportsTo: null,
    capabilities: "Software architecture specialist for system design, scalability, and technical decision-making. Use PROACTIVELY when planning new features, refactoring large systems, or making architectural decisions.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "architect.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "build-error-resolver",
    role: "staff",
    title: "Build Error Resolver",
    status: "idle",
    reportsTo: leadMap['super-architect'],
    capabilities: "Build and TypeScript error resolution specialist. Use PROACTIVELY when build fails or type errors occur. Fixes build/type errors only with minimal diffs, no architectural edits. Focuses on getting the build green quickly.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "build-error-resolver.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "code-reviewer",
    role: "staff",
    title: "Code Reviewer",
    status: "idle",
    reportsTo: leadMap['super-architect'],
    capabilities: "Expert code review specialist. Proactively reviews code for quality, security, and maintainability. Use immediately after writing or modifying code. MUST BE USED for all code changes.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "code-reviewer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "conversion-engineer",
    role: "staff",
    title: "Conversion Engineer",
    status: "idle",
    reportsTo: leadMap['growth-strategist'],
    capabilities: "|   CRO (Conversion Rate Optimization) and Funnel specialist. Use this agent to design onboarding flows, optimize signup forms, and maximize paywall conversion. It focuses on the bridge between Engineering and Revenue.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "conversion-engineer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "cyber-intel",
    role: "staff",
    title: "Cyber Intel",
    status: "idle",
    reportsTo: leadMap['security-guardian'],
    capabilities: "External Threat & Intel Specialist. Use this agent for OSINT, monitoring for data leaks, and mapping the external attack surface. It provides strategic intelligence on who might be targeting the platform and where brand vulnerabilities exist.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "cyber-intel.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "devops-engineer",
    role: "staff",
    title: "Devops Engineer",
    status: "idle",
    reportsTo: null,
    capabilities: "Infrastructure, Deployment, and CI/CD specialist. Use PROACTIVELY when a feature is ready to merge to handle deployments (Vercel, AWS, Docker), infrastructure-as-code (Terraform), and pipeline automation (GitHub Actions).",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "devops-engineer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "doc-updater",
    role: "staff",
    title: "Doc Updater",
    status: "idle",
    reportsTo: null,
    capabilities: "Documentation and codemap specialist. Use PROACTIVELY for updating codemaps and documentation. Runs /update-codemaps and /update-docs, generates docs/CODEMAPS/*, updates READMEs and guides.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "doc-updater.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "e2e-runner",
    role: "staff",
    title: "E2E Runner",
    status: "idle",
    reportsTo: leadMap['super-architect'],
    capabilities: "End-to-end testing specialist using Playwright. Use PROACTIVELY for generating, maintaining, and running E2E tests. Manages test journeys, quarantines flaky tests, uploads artifacts (screenshots, videos, traces), and ensures critical user flows work.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "e2e-runner.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "elite-developer",
    role: "staff",
    title: "Elite Developer",
    status: "idle",
    reportsTo: leadMap['super-architect'],
    capabilities: "Principal Full-Stack Engineer for surgical implementation, strict TDD, complex debugging, and UI construction. Enforces the 1-Man Army pipeline and high-rigor engineering standards. This agent contains the full knowledge of TDD, Systematic Debugging, Build Error Resolution, and Refactoring.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "elite-developer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "experimentation-engineer",
    role: "staff",
    title: "Experimentation Engineer",
    status: "idle",
    reportsTo: null,
    capabilities: "Hypothesis & Experimentation Specialist. Use this agent to design A/B tests, optimize form completion rates, and manage the experiment lifecycle. It ensures that UI changes are driven by statistical evidence, not opinions.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "experimentation-engineer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "growth-engineer",
    role: "staff",
    title: "Growth Engineer",
    status: "idle",
    reportsTo: leadMap['growth-strategist'],
    capabilities: "Engineering-as-Marketing Specialist. Use this agent to build viral referral loops, free utility tools for lead generation, and programmatic SEO pages at scale. It focuses on the \"Inbound\" part of the 1-Man Army pipeline.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "growth-engineer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "interface-designer",
    role: "staff",
    title: "Interface Designer",
    status: "idle",
    reportsTo: null,
    capabilities: "|   Specialist in module interface and API design. Use this agent to generate multiple radically different architectural designs for a system before implementation. It enforces the 'design-an-interface' skill to ensure clean, decoupled, and testable abstractions.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "interface-designer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "perseus",
    role: "staff",
    title: "Perseus",
    status: "idle",
    reportsTo: leadMap['security-guardian'],
    capabilities: "Advanced Offensive Security & Pentesting Specialist. Use this agent for red teaming, penetration testing, and identifying complex security flaws. It leverages specialized security tools for XSS, SQLi, JWT, OAuth2, and network-level vulnerability testing.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "perseus.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "planner",
    role: "staff",
    title: "Planner",
    status: "idle",
    reportsTo: leadMap['product-manager'],
    capabilities: "Expert planning specialist for complex features and refactoring. Use PROACTIVELY when users request feature implementation, architectural changes, or complex refactoring. Automatically activated for planning tasks.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "planner.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "qa-automation-engineer",
    role: "staff",
    title: "Qa Automation Engineer",
    status: "idle",
    reportsTo: leadMap['super-architect'],
    capabilities: "|   E2E Testing and Browser Automation specialist. Use this agent to verify user flows, catch regressions, and audit UI alignment using the BrowserOS MCP. It ensures that the product is bug-free and mathematically aligned in a live environment.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "qa-automation-engineer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "refactor-cleaner",
    role: "staff",
    title: "Refactor Cleaner",
    status: "idle",
    reportsTo: leadMap['super-architect'],
    capabilities: "Dead code cleanup and consolidation specialist. Use PROACTIVELY for removing unused code, duplicates, and refactoring. Runs analysis tools (knip, depcheck, ts-prune) to identify dead code and safely removes it.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "refactor-cleaner.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "release-manager",
    role: "staff",
    title: "Release Manager",
    status: "idle",
    reportsTo: null,
    capabilities: "Release Orchestration & Versioning Specialist. Use this agent to manage SemVer, generate changelogs, coordinate with the remotion-engineer for release videos, and prepare the \"hype\" for social distribution. It ensures every deployment is a \"moment\".",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "release-manager.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "remotion-engineer",
    role: "staff",
    title: "Remotion Engineer",
    status: "idle",
    reportsTo: leadMap['super-architect'],
    capabilities: "Remotion specialist for programmatic video generation using React. Use PROACTIVELY when the user wants to create, debug, or optimize Remotion video projects. Specializes in frame-perfect animations, physics-based motion, and FFmpeg rendering optimization.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "remotion-engineer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "retention-specialist",
    role: "staff",
    title: "Retention Specialist",
    status: "idle",
    reportsTo: leadMap['growth-strategist'],
    capabilities: "LTV & Engagement Specialist. Use this agent to design email sequences, improve the first 5 minutes of the product (onboarding), and apply behavioral psychology to increase retention. It focuses on the \"Active Users\" part of the 1-Man Army pipeline.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "retention-specialist.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "revenue-architect",
    role: "staff",
    title: "Revenue Architect",
    status: "idle",
    reportsTo: null,
    capabilities: "|   Monetization and pricing strategy specialist. Use this agent to design revenue models, set price points based on value perception, and create viral referral loops. It focuses on the \"Cuan\" (Revenue) aspect of the 1-Man Army pipeline.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "revenue-architect.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "security-reviewer",
    role: "staff",
    title: "Security Reviewer",
    status: "idle",
    reportsTo: leadMap['security-guardian'],
    capabilities: "Security vulnerability detection and remediation specialist. Use PROACTIVELY after writing code that handles user input, authentication, API endpoints, or sensitive data. Flags secrets, SSRF, injection, unsafe crypto, and OWASP Top 10 vulnerabilities.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "security-reviewer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "social-strategist",
    role: "staff",
    title: "Social Strategist",
    status: "idle",
    reportsTo: leadMap['growth-strategist'],
    capabilities: "|   Social media and distribution specialist. Use this agent to create hype, draft Twitter/LinkedIn threads, and manage the social media distribution of new features. It focuses on the \"Distribution\" aspect of the 1-Man Army pipeline.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "social-strategist.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "support-lead",
    role: "staff",
    title: "Support Lead",
    status: "idle",
    reportsTo: null,
    capabilities: "User Education & Support Specialist. Use this agent to generate FAQs, troubleshoot from code logic, and manage documentation as a first line of defense. It turns technical complexity into accessible guides for users.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "support-lead.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "tdd-guide",
    role: "staff",
    title: "Tdd Guide",
    status: "idle",
    reportsTo: null,
    capabilities: "Test-Driven Development specialist enforcing write-tests-first methodology. Use PROACTIVELY when writing new features, fixing bugs, or refactoring code. Ensures 80%+ test coverage.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "tdd-guide.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "ui-ux-designer",
    role: "staff",
    title: "Ui Ux Designer",
    status: "idle",
    reportsTo: null,
    capabilities: "|   UI/UX and Frontend Design specialist. Use this agent to generate high-fidelity UI components, manage design tokens, and enforce aesthetic consistency using the Stitch MCP. It transforms design intent into production-ready React/Tailwind code.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "ui-ux-designer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "vercel-react-expert",
    role: "staff",
    title: "Vercel React Expert",
    status: "idle",
    reportsTo: leadMap['super-architect'],
    capabilities: "|   React and Next.js performance optimization specialist. Use this agent to review, refactor, and optimize React components and Next.js pages for maximum speed and Vercel-specific deployment standards. It enforces the 'vercel-react-best-practices' skill.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "vercel-react-expert.md"] },
    budgetMonthlyCents: 50000,
  },
]);

console.log("Galyarder Hierarchical Seed complete");
process.exit(0);
