import { createDb } from "./client.js";
import { companies, agents } from "./schema/index.js";

const url = process.env.DATABASE_URL;
if (!url) throw new Error("DATABASE_URL is required");

const db = createDb(url);

console.log("Seeding Galyarder Digital Company...");

const [company] = await db
  .insert(companies)
  .values({
    name: "Galyarder Digital Company",
    description: "The autonomous workforce for solo founders.",
    status: "active",
    brandColor: "#06b6d4",
    issuePrefix: "GAL",
    budgetMonthlyCents: 1000000,
  })
  .returning();

const companyId = company!.id;

const agentEntries = [
  {
    companyId,
    name: "analytics-architect",
    role: "manager",
    title: "analytics-architect",
    status: "idle",
    capabilities: "Data Infrastructure & Tracking Specialist. Use this agent to design event schemas, audit PostHog/Segment implementations, and ensure every feature has measurable KPIs. It focuses on the \"Measure\" part of the Build-Measure-Learn loop.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "analytics-architect.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "architect",
    role: "manager",
    title: "architect",
    status: "idle",
    capabilities: "Software architecture specialist for system design, scalability, and technical decision-making. Use PROACTIVELY when planning new features, refactoring large systems, or making architectural decisions.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "architect.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "build-error-resolver",
    role: "manager",
    title: "build-error-resolver",
    status: "idle",
    capabilities: "Build and TypeScript error resolution specialist. Use PROACTIVELY when build fails or type errors occur. Fixes build/type errors only with minimal diffs, no architectural edits. Focuses on getting the build green quickly.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "build-error-resolver.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "code-reviewer",
    role: "manager",
    title: "code-reviewer",
    status: "idle",
    capabilities: "Expert code review specialist. Proactively reviews code for quality, security, and maintainability. Use immediately after writing or modifying code. MUST BE USED for all code changes.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "code-reviewer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "conversion-engineer",
    role: "manager",
    title: "conversion-engineer",
    status: "idle",
    capabilities: "|",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "conversion-engineer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "cyber-intel",
    role: "manager",
    title: "cyber-intel",
    status: "idle",
    capabilities: "External Threat & Intel Specialist. Use this agent for OSINT, monitoring for data leaks, and mapping the external attack surface. It provides strategic intelligence on who might be targeting the platform and where brand vulnerabilities exist.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "cyber-intel.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "devops-engineer",
    role: "manager",
    title: "devops-engineer",
    status: "idle",
    capabilities: "Infrastructure, Deployment, and CI/CD specialist. Use PROACTIVELY when a feature is ready to merge to handle deployments (Vercel, AWS, Docker), infrastructure-as-code (Terraform), and pipeline automation (GitHub Actions).",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "devops-engineer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "doc-updater",
    role: "manager",
    title: "doc-updater",
    status: "idle",
    capabilities: "Documentation and codemap specialist. Use PROACTIVELY for updating codemaps and documentation. Runs /update-codemaps and /update-docs, generates docs/CODEMAPS/*, updates READMEs and guides.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "doc-updater.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "e2e-runner",
    role: "manager",
    title: "e2e-runner",
    status: "idle",
    capabilities: "End-to-end testing specialist using Playwright. Use PROACTIVELY for generating, maintaining, and running E2E tests. Manages test journeys, quarantines flaky tests, uploads artifacts (screenshots, videos, traces), and ensures critical user flows work.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "e2e-runner.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "elite-developer",
    role: "manager",
    title: "elite-developer",
    status: "idle",
    capabilities: "Principal Full-Stack Engineer for surgical implementation, strict TDD, complex debugging, and UI construction. Enforces the 1-Man Army pipeline and high-rigor engineering standards. This agent contains the full knowledge of TDD, Systematic Debugging, Build Error Resolution, and Refactoring.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "elite-developer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "experimentation-engineer",
    role: "manager",
    title: "experimentation-engineer",
    status: "idle",
    capabilities: "Hypothesis & Experimentation Specialist. Use this agent to design A/B tests, optimize form completion rates, and manage the experiment lifecycle. It ensures that UI changes are driven by statistical evidence, not opinions.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "experimentation-engineer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "finops-manager",
    role: "manager",
    title: "finops-manager",
    status: "idle",
    capabilities: "Finance & Cloud Cost Specialist. Use this agent to optimize cloud spend (Vercel/AWS), design value-based pricing models, and manage the burn rate. It ensures the 1-Man Army remains profitable and financially sustainable.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "finops-manager.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "fundraising-operator",
    role: "manager",
    title: "fundraising-operator",
    status: "idle",
    capabilities: "Fundraising and investor operations specialist. Owns founder context, pitch narrative, investor targeting, investor communication, diligence readiness, and board-update hygiene for the 1-Man Army founder.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "fundraising-operator.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "growth-engineer",
    role: "manager",
    title: "growth-engineer",
    status: "idle",
    capabilities: "Engineering-as-Marketing Specialist. Use this agent to build viral referral loops, free utility tools for lead generation, and programmatic SEO pages at scale. It focuses on the \"Inbound\" part of the 1-Man Army pipeline.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "growth-engineer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "growth-strategist",
    role: "manager",
    title: "growth-strategist",
    status: "idle",
    capabilities: "|",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "growth-strategist.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "interface-designer",
    role: "manager",
    title: "interface-designer",
    status: "idle",
    capabilities: "|",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "interface-designer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "legal-counsel",
    role: "manager",
    title: "legal-counsel",
    status: "idle",
    capabilities: "Legal & Compliance Specialist. Use this agent to generate TOS/Privacy policies, audit GDPR/CCPA compliance, review open-source licenses, and ensure AI governance (ISO 42001). It protects the 1-Man Army from legal liabilities.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "legal-counsel.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "obsidian-architect",
    role: "manager",
    title: "obsidian-architect",
    status: "idle",
    capabilities: "|",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "obsidian-architect.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "perseus",
    role: "manager",
    title: "perseus",
    status: "idle",
    capabilities: "Advanced Offensive Security & Pentesting Specialist. Use this agent for red teaming, penetration testing, and identifying complex security flaws. It leverages specialized security tools for XSS, SQLi, JWT, OAuth2, and network-level vulnerability testing.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "perseus.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "planner",
    role: "manager",
    title: "planner",
    status: "idle",
    capabilities: "Expert planning specialist for complex features and refactoring. Use PROACTIVELY when users request feature implementation, architectural changes, or complex refactoring. Automatically activated for planning tasks.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "planner.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "product-manager",
    role: "manager",
    title: "product-manager",
    status: "idle",
    capabilities: "Product Management specialist. Focuses on ROI, feature prioritization, Linear ticket management, and ensuring engineering efforts directly impact user acquisition or revenue. Use PROACTIVELY before any code is written to convert PRDs into actionable Linear Epics and Issues.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "product-manager.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "qa-automation-engineer",
    role: "manager",
    title: "qa-automation-engineer",
    status: "idle",
    capabilities: "|",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "qa-automation-engineer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "refactor-cleaner",
    role: "manager",
    title: "refactor-cleaner",
    status: "idle",
    capabilities: "Dead code cleanup and consolidation specialist. Use PROACTIVELY for removing unused code, duplicates, and refactoring. Runs analysis tools (knip, depcheck, ts-prune) to identify dead code and safely removes it.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "refactor-cleaner.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "release-manager",
    role: "manager",
    title: "release-manager",
    status: "idle",
    capabilities: "Release Orchestration & Versioning Specialist. Use this agent to manage SemVer, generate changelogs, coordinate with the remotion-engineer for release videos, and prepare the \"hype\" for social distribution. It ensures every deployment is a \"moment\".",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "release-manager.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "remotion-engineer",
    role: "manager",
    title: "remotion-engineer",
    status: "idle",
    capabilities: "Remotion specialist for programmatic video generation using React. Use PROACTIVELY when the user wants to create, debug, or optimize Remotion video projects. Specializes in frame-perfect animations, physics-based motion, and FFmpeg rendering optimization.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "remotion-engineer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "retention-specialist",
    role: "manager",
    title: "retention-specialist",
    status: "idle",
    capabilities: "LTV & Engagement Specialist. Use this agent to design email sequences, improve the first 5 minutes of the product (onboarding), and apply behavioral psychology to increase retention. It focuses on the \"Active Users\" part of the 1-Man Army pipeline.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "retention-specialist.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "revenue-architect",
    role: "manager",
    title: "revenue-architect",
    status: "idle",
    capabilities: "|",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "revenue-architect.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "security-guardian",
    role: "manager",
    title: "security-guardian",
    status: "idle",
    capabilities: "Security vulnerability detection and remediation specialist. Audits code for OWASP Top 10, IDOR, SSRF, and injection. Enforces zero trust and secure data handling for financial and AI platforms. Contains full knowledge of security reviewer and audit checklists.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "security-guardian.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "security-reviewer",
    role: "manager",
    title: "security-reviewer",
    status: "idle",
    capabilities: "Security vulnerability detection and remediation specialist. Use PROACTIVELY after writing code that handles user input, authentication, API endpoints, or sensitive data. Flags secrets, SSRF, injection, unsafe crypto, and OWASP Top 10 vulnerabilities.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "security-reviewer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "social-strategist",
    role: "manager",
    title: "social-strategist",
    status: "idle",
    capabilities: "|",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "social-strategist.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "super-architect",
    role: "manager",
    title: "super-architect",
    status: "idle",
    capabilities: "Software architecture specialist for system design, scalability, and technical decision-making. Produces ADRs, Vertical Slice plans, and enforces deep module design for the 1-Man Army pipeline. Contains the full knowledge of Architecture Patterns, Systems Design, and Planning.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "super-architect.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "support-lead",
    role: "manager",
    title: "support-lead",
    status: "idle",
    capabilities: "User Education & Support Specialist. Use this agent to generate FAQs, troubleshoot from code logic, and manage documentation as a first line of defense. It turns technical complexity into accessible guides for users.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "support-lead.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "tdd-guide",
    role: "manager",
    title: "tdd-guide",
    status: "idle",
    capabilities: "Test-Driven Development specialist enforcing write-tests-first methodology. Use PROACTIVELY when writing new features, fixing bugs, or refactoring code. Ensures 80%+ test coverage.",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "tdd-guide.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "ui-ux-designer",
    role: "manager",
    title: "ui-ux-designer",
    status: "idle",
    capabilities: "|",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "ui-ux-designer.md"] },
    budgetMonthlyCents: 50000,
  },
  {
    companyId,
    name: "vercel-react-expert",
    role: "manager",
    title: "vercel-react-expert",
    status: "idle",
    capabilities: "|",
    adapterType: "process",
    adapterConfig: { command: "rtk", args: ["gemini", "run", "--agent", "vercel-react-expert.md"] },
    budgetMonthlyCents: 50000,
  },
];

await db.insert(agents).values(agentEntries);

console.log("Galyarder Seed complete");
process.exit(0);
